
### Questions source
https://www.digitalocean.com/community/tutorials/java-programming-interview-questions#5-write-a-java-program-to-print-a-fibonacci-sequence-using-recursion

###
GET http://localhost:8080/exam/get/java/1
###
GET http://localhost:8080/exam/get/java/2
###
GET http://localhost:8080/exam/get/java/3
###
GET http://localhost:8080/exam/get/java/10
###
GET http://localhost:8080/exam/get/java/12
###
GET http://localhost:8080/exam/get/java/13
###
GET http://localhost:8080/exam/get/math/1
###
GET http://localhost:8080/exam/get/math/2
###
GET http://localhost:8080/exam/get/math/3
###
GET http://localhost:8080/exam/get/math/10
###
GET http://localhost:8080/exam/get/math/12
###
GET http://localhost:8080/exam/get/math/13



###
GET http://localhost:8080/exam/java/add?question=What is a maximal size of bucket list within HashSet before it will be transformed to a tree?&answer=8;
###
GET http://localhost:8080/exam/java/add?question=What is Integer.MAX_VALUE equal to?&answer=2147483647
###
GET http://localhost:8080/exam/java
###
GET http://localhost:8080/exam/java/remove?question=What is Integer.MAX_VALUE equal to?

###
GET http://localhost:8080/exam/math/add?question=-1*-1&answer=1;
###
GET http://localhost:8080/exam/math/add?question=3+3&answer=6
###
GET http://localhost:8080/exam/math
###
GET http://localhost:8080/exam/math/remove?question=3+3
